import { ICard } from "./ICard";

export const CardsInitial: ICard[] = [
  {
    id: 1,
    face: "./cards/cat_1.png",
    back: "./cards/backcard_1.png",
    opened: false,
    completed: false,
  },
  {
    id: 2,
    face: "./cards/cat_2.png",
    back: "./cards/backcard_2.png",
    opened: false,
    completed: false,
  },
  {
    id: 3,
    face: "./cards/cat_3.png",
    back: "./cards/backcard_3.png",
    opened: false,
    completed: false,
  },
  {
    id: 4,
    face: "./cards/cat_4.png",
    back: "./cards/backcard_4.png",
    opened: false,
    completed: false,
  },
  {
    id: 5,
    face: "./cards/cat_5.png",
    back: "./cards/backcard_5.png",
    opened: false,
    completed: false,
  },
  {
    id: 6,
    face: "./cards/cat_6.png",
    back: "./cards/backcard_6.png",
    opened: false,
    completed: false,
  },
  {
    id: 7,
    face: "./cards/cat_7.png",
    back: "./cards/backcard_7.png",
    opened: false,
    completed: false,
  },
  {
    id: 8,
    face: "./cards/cat_8.png",
    back: "./cards/backcard_8.png",
    opened: false,
    completed: false,
  },
  {
    id: 9,
    face: "./cards/cat_9.png",
    back: "./cards/backcard_9.png",
    opened: false,
    completed: false,
  },
  {
    id: 10,
    face: "./cards/cat_10.png",
    back: "./cards/backcard_10.png",
    opened: false,
    completed: false,
  },
  {
    id: 11,
    face: "./cards/cat_11.png",
    back: "./cards/backcard_11.png",
    opened: false,
    completed: false,
  },
  {
    id: 12,
    face: "./cards/cat_12.png",
    back: "./cards/backcard_12.png",
    opened: false,
    completed: false,
  },
  {
    id: 13,
    face: "./cards/cat_13.png",
    back: "./cards/backcard_13.png",
    opened: false,
    completed: false,
  },
  {
    id: 14,
    face: "./cards/cat_14.png",
    back: "./cards/backcard_14.png",
    opened: false,
    completed: false,
  },
  {
    id: 15,
    face: "./cards/cat_15.png",
    back: "./cards/backcard_15.png",
    opened: false,
    completed: false,
  },
  {
    id: 16,
    face: "./cards/cat_16.png",
    back: "./cards/backcard_16.png",
    opened: false,
    completed: false,
  },
  {
    id: 17,
    face: "./cards/cat_17.png",
    back: "./cards/backcard_17.png",
    opened: false,
    completed: false,
  },
  {
    id: 18,
    face: "./cards/cat_18.png",
    back: "./cards/backcard_18.png",
    opened: false,
    completed: false,
  },
  {
    id: 19,
    face: "./cards/cat_19.png",
    back: "./cards/backcard_19.png",
    opened: false,
    completed: false,
  },
  {
    id: 20,
    face: "./cards/cat_20.png",
    back: "./cards/backcard_20.png",
    opened: false,
    completed: false,
  },
  {
    id: 21,
    face: "./cards/cat_21.png",
    back: "./cards/backcard_21.png",
    opened: false,
    completed: false,
  },
  {
    id: 22,
    face: "./cards/cat_22.png",
    back: "./cards/backcard_22.png",
    opened: false,
    completed: false,
  },
  {
    id: 23,
    face: "./cards/cat_23.png",
    back: "./cards/backcard_23.png",
    opened: false,
    completed: false,
  },
  {
    id: 24,
    face: "./cards/cat_24.png",
    back: "./cards/backcard_24.png",
    opened: false,
    completed: false,
  },
  {
    id: 25,
    face: "./cards/cat_25.png",
    back: "./cards/backcard_25.png",
    opened: false,
    completed: false,
  },
  {
    id: 26,
    face: "./cards/cat_26.png",
    back: "./cards/backcard_26.png",
    opened: false,
    completed: false,
  },
  {
    id: 27,
    face: "./cards/cat_27.png",
    back: "./cards/backcard_27.png",
    opened: false,
    completed: false,
  },
  {
    id: 28,
    face: "./cards/cat_28.png",
    back: "./cards/backcard_28.png",
    opened: false,
    completed: false,
  },
];
